# # Stage 1: Build
# FROM node:22-alpine AS build

# WORKDIR /usr/src/app

# COPY package.json package-lock.json ./

# RUN npm install

# COPY . .

# RUN npx tsc

# # Stage 2: Production
# FROM node:22-alpine AS production

# WORKDIR /usr/src/app

# COPY package.json package-lock.json ./
# RUN npm ci --omit=dev

# COPY --from=build /usr/src/app/dist ./dist

# EXPOSE 5000

# ENV NODE_ENV=production

# CMD ["node", "dist/server.js"]